"""Version information."""
__title__ = "nhppy"
__description__ = "Realizations of stochastic processes, mainly (Non-Homogeneous/multidimensional) Poisson processes."
__long_description__ = "Stochastic processes are used to model the evolution of a random system over time and space. They can be used to model the growth of bacteria, the impact position of rain drops, the position of a moving pollen particle in air, etc. Built upon the foundation of laid by Christopher Flynn in the stochastic package, an extension providing more general Poisson processes was added. The titular NHPPy, the non-homogeneous Python process has a rate function that can vary arbitrarily. Other poisson processes included the Mixed poisson process, whose rate is a random variable, and the doubly stochastic poisson process (or Cox process) whose rate function is itself a stochastic process. The Poisson processes were also extended to multiple dimensions. Some analysis tools of points in space were also added: notably the Komogorov Smyrnov-test in one and two dimension, which determines the likelihood that two datasets were generated from the same dsitribution."
__url__ = ""
__version__ = "0.1.0"
__author__ = "Gabriel Taillon"
__author_email__ = "ga.taillon@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2018 Gabriel Taillon \n Copyright 2018 Christopher Flynn"
__docs_copyright__ = "2018 Gabriel Taillon \n 2018 Christopher Flynn"
