"""Module level accessible objects."""
from stochastic._version import __author__
from stochastic._version import __author_email__
from stochastic._version import __copyright__
from stochastic._version import __description__
from stochastic._version import __docs_copyright__
from stochastic._version import __license__
from stochastic._version import __title__
from stochastic._version import __url__
from stochastic._version import __version__
