"""Version information."""
__title__ = "NHPPy"
__description__ = "Realizations of stochastic processes, mainly (Non-Homogeneous/multidimensional) Poisson processes."
__url__ = ""
__version__ = "0.1.0"
__author__ = "Gabriel Taillon"
__author_email__ = "ga.taillon@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2018 Gabriel Taillon \n Copyright 2018 Christopher Flynn"
__docs_copyright__ = "2018 Gabriel Taillon \n 2018 Christopher Flynn"
