"""Version information."""
__title__ = "stochastic"
__description__ = "Stochastic process realizations."
__url__ = "https://github.com/crflynn/stochastic"
__version__ = "0.7.0"
__author__ = "Christopher Flynn"
__author_email__ = "crf204@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2018-2020 Christopher Flynn"
__docs_copyright__ = "2018-2020 Christopher Flynn"
